export const GET_BURGER_REQUEST = "GET_BURGER_REQUEST";
export const GET_BURGER_SUCCESS = "GET_BURGER_SUCCESS";
export const GET_BURGER_FAILURE = "GET_BURGER_FAILURE";

export const GET_MUFFIN_REQUEST = "GET_MUFFIN_REQUEST";
export const GET_MUFFIN_SUCCESS = "GET_MUFFIN_SUCCESS";
export const GET_MUFFIN_FAILURE = "GET_MUFFIN_FAILURE";

export const GET_CHICKENANDFISH_REQUEST = "GET_CHICKENANDFISH_REQUEST";
export const GET_CHICKENANDFISH_SUCCESS = "GET_CHICKENANDFISH_SUCCESS";
export const GET_CHICKENANDFISH_FAILURE = "GET_CHICKENANDFISH_FAILURE";

export const GET_CRISPYCHICKEN_REQUEST = "GET_CRISPYCHICKEN_REQUEST";
export const GET_CRISPYCHICKEN_SUCCESS = "GET_CRISPYCHICKEN_SUCCESS";
export const GET_CRISPYCHICKEN_FAILURE = "GET_CRISPYCHICKEN_FAILURE";

export const GET_WRAPS_REQUEST = "GET_WRAPS_REQUEST";
export const GET_WRAPS_SUCCESS = "GET_WRAPS_SUCCESS";
export const GET_WRAPS_FAILURE = "GET_WRAPS_FAILURE";

export const GET_HAPPYMEAL_REQUEST = "GET_HAPPYMEAL_REQUEST";
export const GET_HAPPYMEAL_SUCCESS = "GET_HAPPYMEAL_SUCCESS";
export const GET_HAPPYMEAL_FAILURE = "GET_HAPPYMEAL_FAILURE";

export const GET_EXTRAVALUEMEAL_REQUEST = "GET_EXTRAVALUEMEAL_REQUEST";
export const GET_EXTRAVALUEMEAL_SUCCESS = "GET_EXTRAVALUEMEAL_SUCCESS";
export const GET_EXTRAVALUEMEAL_FAILURE = "GET_EXTRAVALUEMEAL_FAILURE";

export const GET_VALUEMEAL_REQUEST = "GET_VALUEMEAL_REQUEST";
export const GET_VALUEMEAL_SUCCESS = "GET_VALUEMEAL_SUCCESS";
export const GET_VALUEMEAL_FAILURE = "GET_VALUEMEAL_FAILURE";

export const GET_DESSERTS_REQUEST = "GET_DESSERTS_REQUEST";
export const GET_DESSERTS_SUCCESS = "GET_DESSERTS_SUCCESS";
export const GET_DESSERTS_FAILURE = "GET_DESSERTS_FAILURE";

export const GET_BEVERAGES_REQUEST = "GET_BEVERAGES_REQUEST";
export const GET_BEVERAGES_SUCCESS = "GET_BEVERAGES_SUCCESS";
export const GET_BEVERAGES_FAILURE = "GET_BEVERAGES_FAILURE";

export const GET_MCCAFE_REQUEST = "GET_MCCAFE_REQUEST";
export const GET_MCCAFE_SUCCESS = "GET_MCCAFE_SUCCESS";
export const GET_MCCAFE_FAILURE = "GET_MCCAFE_FAILURE";

export const GET_FRIESANDSIDES_REQUEST = "GET_FRIESANDSIDES_REQUEST";
export const GET_FRIESANDSIDES_SUCCESS = "GET_FRIESANDSIDES_SUCCESS";
export const GET_FRIESANDSIDES_FAILURE = "GET_FRIESANDSIDES_FAILURE";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const EMPTY_CART = "EMPTY_CART";

export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";