import Mcdonaldslogo from '../images/McDonalds_Logo.png'
import MenuImg1 from '../images/menu-img-1.jpg'
import MenuImg2 from '../images/menu-img-2.jpg'
import MenuImg3 from '../images/menu-img-3.jpg'
import MenuImg4 from '../images/menu-img-4.png'
import MenuImg5 from '../images/menu-img-5.png'
import MenuImg6 from '../images/menu-img-6.jpg'
import MenuImg7 from '../images/menu-img-7.jpg'
import MenuImg8 from '../images/menu-img-8.png'
import MenuImg9 from '../images/menu-img-9.jpg'
import MenuImg10 from '../images/menu-img-10.jpg'
import MenuImg11 from '../images/menu-img-11.jpg'
import MenuImg12 from '../images/menu-img-12.jpg'
import appstore from '../images/download.svg'
import playstore from '../images/get.svg'
import homeimg1 from '../images/home-img-1.png'
import homeimg2 from '../images/home-img-2.png'
import homeimg3 from '../images/home-img-3.png'
import homeimg4 from '../images/home-img-4.png'
import homeimg5 from '../images/home-img-5.png'
import homeimg6 from '../images/home-img-6.jpg'
import bodyimg1 from '../images/home-body-img-1.jpg'
import bodyimg2 from '../images/home-body-img-2.jpg'
import bodyimg3 from '../images/home-body-img-3.jpg'
import bodyimg4 from '../images/home-body-img-4.png'
import bodyimg5 from '../images/home-body-img-5.png'
import bodyimg6 from '../images/home-body-img-6.png'
import community from '../images/Our-Community.png'
import history from '../images/Our-History.png'
import contactUs from '../images/Contact-Us.png'
import privacypolicy from '../images/Privacy-Policy.png'
import termsandcondition from '../images/terms-and-condition.png'
import suggestionribbon from '../images/suggestion-ribbon.png'
import complaintribbon from '../images/compaint-ribbon.png'
import breakfastpancakeimg1 from '../images/breakfast-pancake-img-1.png'
import breakfastpancakeimg2 from '../images/breakfast-pancake-img-2.png'
import breakfastpancakeimg3 from '../images/breakfast-pancake-img-3.png'
import breakfastpancakeimg4 from '../images/breakfast-pancake-img-4.png'
import breakfastpancakeimg5 from '../images/breakfast-pancake-img-5.png'
import breakfastpancakeimg6 from '../images/breakfast-pancake-img-6.png'
import breakfastpancakeimg7 from '../images/breakfast-pancake-img-7.png'
import breakfastpancakeimg8 from '../images/breakfast-pancake-img-8.png'
import beefimg1 from '../images/beef-img-1.png'
import beefimg2 from '../images/beef-img-2.png'
import beefimg3 from '../images/beef-img-3.png'
import beefimg4 from '../images/beef-img-4.png'
import chickenandfishimage1 from '../images/chicken&fish-1.png'
import chickenandfishimage2 from '../images/chicken&fish-2.png'
import chickenandfishimage3 from '../images/chicken&fish-3.png'
import chickenandfishimage4 from '../images/chicken&fish-4.png'
import chickenandfishimage5 from '../images/chicken&fish-5.png'
import chickenandfishimage6 from '../images/chicken&fish-6.png'
import chickenandfishimage7 from '../images/chicken&fish-7.png'
import chickenandfishimage8 from '../images/chicken&fish-8.png'
import chickenandfishimage9 from '../images/chicken&fish-9.png'
import chickenandfishimage10 from '../images/chicken&fish10.png'
import chickenandfishimage11 from '../images/chicken&fish11.png'

export {Mcdonaldslogo, MenuImg1, MenuImg2, MenuImg3, MenuImg4, MenuImg5,
     MenuImg6, MenuImg7, MenuImg8, MenuImg9, MenuImg10, MenuImg11, MenuImg12,
      appstore, playstore, homeimg1, homeimg2, homeimg3, homeimg4, homeimg5,
       homeimg6, bodyimg1, bodyimg2, bodyimg3, bodyimg4, bodyimg5, bodyimg6,
       community, history, contactUs, privacypolicy, termsandcondition, suggestionribbon, complaintribbon,
       breakfastpancakeimg2, breakfastpancakeimg3, breakfastpancakeimg4, breakfastpancakeimg5,
       breakfastpancakeimg1, breakfastpancakeimg6, breakfastpancakeimg7, breakfastpancakeimg8,
       beefimg1, beefimg2, beefimg3, beefimg4, chickenandfishimage1, chickenandfishimage2, chickenandfishimage3,
        chickenandfishimage4, chickenandfishimage5, chickenandfishimage6, chickenandfishimage7,
         chickenandfishimage8, chickenandfishimage9, chickenandfishimage10, chickenandfishimage11}